---

  - name: Install frontend dependencies
    yum: name={{ item }} state=latest
    with_items:
      - npm

  - name: Install frontend dependencies based on package.json
    npm: path={{ app_frontend_path }} state=latest
