---

  - include_role: name=update_packages

  - name: Load test data
    shell: su - {{ app_user }} -c '{{ etsin_reindexer_path }}/scripts/load_test_data_to_index.sh'
    when: deployment_environment_id in ['local_development', 'test']
