- name: Copy app config to target VM
  template: src=templates/app_config dest=/home/{{ app_user }}/app_config owner={{ app_user }} group=etsin mode=0440

- name: Create app logging folder to {{ app_log_base_path }}
  file: path={{ app_log_base_path }} state=directory owner={{ app_user }} group=etsin mode=0755

- name: Create folder {{ app_base_path }}
  file: path={{ app_base_path }} state=directory owner={{ app_user }} group=etsin mode=0755

- name: Clone project repo from branch {{ project_repo_branch }} to {{ app_base_path }}
  git: repo={{ project_repo }} dest={{ app_base_path }} version={{ project_repo_branch }}
  become_user: "{{ app_user }}"
  ignore_errors: yes

- name: Install app python package requirements
  pip: requirements={{ app_base_path }}/requirements.txt virtualenv={{ python_virtualenv_path }}
  become_user: "{{ app_user }}"

- name: Symlink pre-commit hook in .githooks/ to .git/hooks/
  shell: cd {{ app_base_path }}/.git/hooks; ln -sfn ../../.githooks/pre-commit pre-commit
  when: deployment_environment_id == 'local_development'

- include_role: name=gunicorn
