---

  - include_role: name=app_config

  - include_role: name=saml_config

  - name: Create web app logging folder to {{ web_app_log_base_path }}
    file: path={{ web_app_log_base_path }} state=directory owner={{ app_user }} group=etsin mode=0755

  - name: Create folder {{ web_app_base_path }} for the web app
    file: path={{ web_app_base_path }} state=directory owner={{ app_user }} group=etsin mode=0755

  - name: Clone project repo from branch {{ web_app_github_repo_branch }} to {{ web_app_base_path }}
    git: repo={{ web_app_github_repo }} dest={{ web_app_base_path }} version={{ web_app_github_repo_branch }}
    become_user: "{{ app_user }}"
    ignore_errors: yes

  - name: Update app python package requirements to their latest versions
    shell: pur --force --requirement {{ web_app_base_path }}/requirements.txt
    become_user: "{{ app_user }}"
    when: deployment_environment_id == 'local_development'

  - name: Install web app python package requirements
    pip: requirements={{ web_app_base_path }}/requirements.txt virtualenv={{ python_virtualenv_path }}
    become_user: "{{ app_user }}"

  - name: Update app python test package requirements to their latest versions
    shell: pur --force --requirement {{ web_app_base_path }}/test_requirements.txt
    become_user: "{{ app_user }}"
    when: deployment_environment_id == 'local_development'

  - name: Install web app python test package requirements
    pip: requirements={{ web_app_base_path }}/test_requirements.txt virtualenv={{ python_virtualenv_path }}
    become_user: "{{ app_user }}"
    when: deployment_environment_id not in ['staging', 'production']

  - include_role: name=gunicorn

  - block:
      - name: Install NPM
        yum: name=npm state=latest
        when: deployment_environment_id != 'local_development'
      - name: Install NPM for local development
        block:
          - name: Enable software collections
            shell: yum --setopt=tsflags=nodocs -y install centos-release-scl-rh
          - name: Install nodejs 12.x
            shell: yum --enablerepo=centos-sclo-rh-testing -y install rh-nodejs12
          - name: link npm to /usr/local/bin/
            shell: ln -s /opt/rh/rh-nodejs12/root/bin/npm /usr/bin/npm
          - name: link node to /usr/local/bin/
            shell: ln -s /opt/rh/rh-nodejs12/root/bin/node /usr/bin/node
          - name: link nodejs to /usr/local/bin/
            shell: ln -s /opt/rh/rh-nodejs12/root/bin/node /usr/bin/nodejs
          - name: link npx to /usr/local/bin/
            shell: ln -s /opt/rh/rh-nodejs12/root/bin/npx /usr/bin/npx
        when: deployment_environment_id == 'local_development'

  - include_role: name=frontend

  - debug:
      msg: "Local dev environment successfully set up. Run commands 'sudo su - {{ app_user }}' and 'runserver' to run the app."
    when: deployment_environment_id == 'local_development'

  - debug:
      msg: "{{ deployment_environment_id }} web app environment successfully set up."
    when: deployment_environment_id != 'local_development'
