- name: Ensure packages required by python saml library requires are present
  shell: yum -y install libxml2-devel xmlsec1-devel xmlsec1-openssl-devel libtool-ltdl-devel warn=false

- name: Copy SAML settings.json to target VM
  template: src=templates/settings.json dest=/home/{{ app_user }}/settings.json owner={{ app_user }} group=etsin mode=0440

- name: Copy SAML advanced_settings.json to target VM
  template: src=templates/advanced_settings.json dest=/home/{{ app_user }}/advanced_settings.json owner={{ app_user }} group=etsin mode=0440
