
- name: Is python virtual env installed?
  stat: path={{ python_virtualenv_path }}
  register: virtualenv_installed

- block:
    - name: Install IUS
      yum: name=https://centos7.iuscommunity.org/ius-release.rpm
      when: deployment_environment_id in ['local_development', 'demo']

    - name: Install Python 3.6
      shell: yum --setopt=tsflags=nodocs -y install python36u python36u-pip python36u-devel
      become: yes
      when:
        - not python36u_installed.stat.exists
        - deployment_environment_id in ['local_development', 'demo']

    - name: Install Python 3.6
      yum: name=rh-python36 state=latest
      when:
        - not rh_python36_installed.stat.exists
        - deployment_environment_id not in ['local_development', 'demo']

    - name: Create virtual environment directory for Python to {{ python_virtualenv_path }}
      file: path={{ python_virtualenv_path }} state=directory owner={{ app_user }} group=etsin mode=0755

    - name: Install virtual environment for Python to {{ python_virtualenv_path }}
      command: /usr/bin/python3 -m venv {{ python_virtualenv_path }}

  when: not virtualenv_installed.stat.exists

- name: Set owner of pyvenv to {{ app_user }} user
  file: path={{ python_virtualenv_path }} owner={{ app_user }} group=etsin recurse=yes mode=0755

- name: install wheel python package to enable using pip for installing requirements as {{ app_user }}
  pip: name=wheel virtualenv={{ python_virtualenv_path }}
  become_user: "{{ app_user }}"
