---

- hosts: dataservers
  vars:
    is_provision: true
  become: yes
  roles:
    - os-base
    - python
    - search_index
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
