---

- hosts: webservers
  vars:
    is_provision: true
  become: yes
  roles:
    - os-base
    - python
    - nginx
    - provision_app
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
