---

- hosts: dataservers
  vars:
    is_provision: true
  become: yes
  roles:
    - os-base
    - python
    - elasticsearch
    - provision_search_app
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
