---

- hosts: dataservers
  become: yes
  roles:
    - os-base
    - update_packages
    - python
    - elasticsearch
    - provision_search_app
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
