---

- hosts: webservers
  become: yes
  roles:
    - { role: os-base, when: "deployment_environment_id != 'local_development'" }
    - { role: update_packages, when: "deployment_environment_id != 'local_development'" }
    - { role: python, when: "deployment_environment_id != 'local_development'" }
    - nginx
    - provision_web_app
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
