---

- include_role: name=update_packages

- name: Get current timestamp
  shell: date +%Y%m%d%H%M%S
  register: timestamp

- name: Backup database
  shell: "pg_dump --format=custom $ETSIN_DATABASE_NAME -f {{ etsin_db_backup_archive_path }}/etsin_db_{{ deployment_environment_id }}_backup_{{ timestamp.stdout }}.dump"
  args:
    executable: /bin/bash
  become_user: postgres

- block:
    - name: Drop current etsin database
      shell: "psql -c 'DROP DATABASE '\"$ETSIN_DATABASE_NAME\"';'"
      args:
        executable: /bin/bash

    - name: Recreate etsin database
      shell: "psql -c 'CREATE DATABASE '\"$ETSIN_DATABASE_NAME\"' WITH OWNER='\"$ETSIN_DATABASE_USER\"' TEMPLATE=template0 ENCODING=\"'\"UTF8\"'\" LC_COLLATE=\"'\"fi_FI.UTF-8\"'\" LC_CTYPE=\"'\"fi_FI.UTF-8\"'\";'"
      args:
        executable: /bin/bash

  become_user: postgres
  when: deployment_environment_id in ['local_development', 'test', 'stable']
